## Inspect an Array 

In [1]:
import numpy as np 

In [2]:
arr = np.array([[1,2,3],[4,5,6]] ,dtype=np.int64 )
arr 

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

### inspect general information of an array

In [3]:
np.info(arr)

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x21d64af70f0
byteorder:  little
byteswap:  False
type: int64


In [ ]:
### inspect the data type of an array
arr.dtype

dtype('int64')

In [5]:
## inspect the dimension of an array
arr.shape

(2, 3)

In [6]:
##inspect length of an array  ( number of row )
len(arr)

2

In [7]:
## inspect the number of elements in an array
arr.size

6

In [8]:
##inspect the number of bytes of each element in an array
arr.itemsize

8

In [9]:
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)

48


In [10]:
print((arr.nbytes)* 8 ) # bits

384


In [12]:
three_D = np.array([ [[2,3],[4,5]] , [[4,3],[2,8]]  ])
print(three_D.shape)
three_D.ndim


(2, 2, 2)


3

In [14]:
four_D = np.array([ [ [ [1,2] , [3,4] ] , [  [5,6],[7,8] ]  ] , [  [ [9,10] , [11, 12] ], [ [13,14] , [15,16]]  ]   ] )
print(four_D.shape)
four_D.ndim

(2, 2, 2, 2)


4

## Sampling Method 

In [16]:
## set seed 
np.random.seed()
np.random.rand(3)


array([0.38990187, 0.1696044 , 0.14209385])

In [17]:
np.random.seed(11)
np.random.rand(4)

array([0.18026969, 0.01947524, 0.46321853, 0.72493393])

In [18]:
##  set random state which is independent from the global seed

rs = np.random.RandomState(23)
rs.rand(10)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584, 0.22104536,
       0.68622209, 0.1671392 , 0.39244247, 0.61805235, 0.41193009])

In [19]:
rs = np.random.RandomState(321)
rs.rand(3)

array([0.88594794, 0.07791236, 0.97964616])

### generate a random sample from interval [0, 1) in a given shape

In [20]:
# generate a random scalar
print(np.random.rand())

0.42020360458772743


In [ ]:
# generate a 1D array
print(np.random.rand(3))

[0.4854271  0.01278081 0.48737161]


In [22]:
# generate a 2D array
print(np.random.rand(3,3))

[[0.94180665 0.85079509 0.72996447]
 [0.10873607 0.89390417 0.85715425]
 [0.16508662 0.63233401 0.02048361]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [23]:
print(np.random.randn(3,3))

[[-0.34842575 -0.72720498  0.47220389]
 [-0.62373696 -0.51521142  1.05537288]
 [-0.71179307 -0.33212692  0.23688037]]


In [24]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[8 8 1]


In [25]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.47979728 0.40167648 0.847979   0.71784918 0.60206405 0.55238382
 0.9491024  0.98667333 0.33805405 0.23987468]
[0.79643575 0.06368643 0.36461564 0.0700228  0.31936771 0.0703826
 0.29026367 0.79010112 0.90540032 0.79262139]
[0.56181871 0.61601839 0.36148354 0.1688173  0.43624093 0.73282534
 0.06288762 0.02073298 0.77054807 0.29995201]
[0.70116428 0.73466772 0.93290463 0.40032843 0.35843793 0.80656679
 0.7644911  0.65261474 0.81096657 0.64221486]


In [26]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[2 1 1 2 1 1 1 1 0 0]


In [27]:
print(np.random.choice(3,10))

[1 1 0 2 1 1 2 0 1 0]


In [28]:
print (np.random.choice([1,2,3], 10))

[2 1 1 3 3 3 1 1 3 1]


In [29]:
### shuffle an array in place

arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.random.shuffle(arr)
arr

array([6, 0, 2, 3, 9, 4, 5, 8, 1, 7])

In [31]:
# generate a permutation of an array
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [4 5 6 7 1 0 9 8 3 2]


#  Math Functions

In [32]:
arr = np.random.rand(5,5)


In [33]:
## element-wise addition, subtraction, multiplication and division

print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.21800338 10.84493853 10.30216469 10.43822067 10.09141459]
 [10.30097917 10.08569481 10.34371331 10.70930102 10.97396826]
 [10.62522484 10.26930354 10.65670881 10.62699782 10.82565223]
 [10.53369398 10.91112166 10.41550367 10.28604467 10.51900774]
 [10.92245024 10.72391126 10.493913   10.49749635 10.6487222 ]]
[[-9.78199662 -9.15506147 -9.69783531 -9.56177933 -9.90858541]
 [-9.69902083 -9.91430519 -9.65628669 -9.29069898 -9.02603174]
 [-9.37477516 -9.73069646 -9.34329119 -9.37300218 -9.17434777]
 [-9.46630602 -9.08887834 -9.58449633 -9.71395533 -9.48099226]
 [-9.07754976 -9.27608874 -9.506087   -9.50250365 -9.3512778 ]]
[[2.18003375 8.44938531 3.02164688 4.38220671 0.91414587]
 [3.0097917  0.85694806 3.43713307 7.09301018 9.73968256]
 [6.2522484  2.6930354  6.56708806 6.26997819 8.25652229]
 [5.33693982 9.11121665 4.15503669 2.86044669 5.19007742]
 [9.22450238 7.23911263 4.93913001 4.97496353 6.48722198]]
[[0.02180034 0.08449385 0.03021647 0.04382207 0.00914146]
 [0.03009792 0.0085

In [34]:
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)


[ 9 11 13]
[1 2 3]
[1 4 9]


In [35]:
# element-wise exponentiation
print(np.exp(arr))


[[1.24359127 2.32783472 1.352784   1.5499469  1.09572318]
 [1.3511812  1.08947378 1.41017429 2.03257003 2.6484333 ]
 [1.86866606 1.30905243 1.92843503 1.87198211 2.28336956]
 [1.70521974 2.48711067 1.51513367 1.33115192 1.68035947]
 [2.51544629 2.06248437 1.63871599 1.64459862 1.91309471]]


In [ ]:
# element-wise logorithm
# natural log
print(np.log(arr))  


[[-1.52324473 -0.1684914  -1.19678309 -0.82503268 -2.39235022]
 [-1.20071422 -2.45696306 -1.06794738 -0.34347528 -0.02637657]
 [-0.46964395 -1.31191613 -0.42051458 -0.46681222 -0.19158162]
 [-0.62793267 -0.09307884 -0.87826383 -1.25160729 -0.65583648]
 [-0.08072185 -0.32308646 -0.70539589 -0.69816705 -0.4327507 ]]


In [38]:
# base 2
print(np.log2(arr))  


[[-2.19757762 -0.24308171 -1.72659302 -1.19027056 -3.4514318 ]
 [-1.73226445 -3.54464842 -1.54072239 -0.49553008 -0.03805334]
 [-0.677553   -1.8926949  -0.60667429 -0.67346767 -0.27639386]
 [-0.90591535 -0.13428438 -1.26706688 -1.80568764 -0.94617204]
 [-0.11645701 -0.46611523 -1.01767115 -1.00724215 -0.62432729]]


In [39]:
# base 10
print(np.log10(arr))

[[-0.66153678 -0.07317488 -0.51975629 -0.35830714 -1.0389845 ]
 [-0.52146356 -1.0670455  -0.46380365 -0.14916942 -0.0114552 ]
 [-0.20396378 -0.56975794 -0.18262716 -0.20273397 -0.08320284]
 [-0.27270769 -0.04042363 -0.38142514 -0.54356614 -0.28482616]
 [-0.03505705 -0.14031467 -0.30634954 -0.3032101  -0.18794124]]


In [ ]:
# element-wise square root
print(np.sqrt(arr))


[[0.46690832 0.91920538 0.54969509 0.66198238 0.30234845]
 [0.54861569 0.29273675 0.58627068 0.84220011 0.9868983 ]
 [0.7907116  0.51894464 0.81037572 0.79183194 0.90865408]
 [0.73054362 0.95452693 0.64459574 0.53483144 0.72042192]
 [0.96044273 0.85082975 0.70278944 0.70533421 0.80543293]]


In [41]:
# element-wise sine and cosine
print(np.sin(arr))

[[0.21628069 0.74793031 0.29758752 0.42432894 0.09128732]
 [0.2964555  0.08558996 0.33698552 0.65130353 0.82712247]
 [0.5852796  0.26606014 0.61051352 0.58671626 0.7349902 ]
 [0.50871708 0.79019166 0.4036508  0.28215983 0.49601879]
 [0.79708363 0.66232013 0.47407485 0.47722688 0.60416867]]


In [42]:
print(np.cos(arr))

[[0.97633123 0.66377726 0.95469454 0.90550812 0.9958246 ]
 [0.95504667 0.99633045 0.94150983 0.75881731 0.56202173]
 [0.81083155 0.96395643 0.79200584 0.80979258 0.67807773]
 [0.86093376 0.61285981 0.91491313 0.95936741 0.86831179]
 [0.60386893 0.74922096 0.88048455 0.87878012 0.79685646]]


In [43]:
# sum along a specified axis
# sum along the row
print(np.sum(arr, axis=0)) 

[2.60035161 2.8349698  2.21200347 2.55806053 3.05876501]


In [44]:
# sum along the column
print(np.sum(arr, axis=1))

[1.89474185 2.41365656 3.00388723 2.66537173 3.28649305]


In [45]:
## compute the min and max along a specified axis
# calculate min along the row
print(np.min(arr, axis=0))

[0.21800338 0.08569481 0.30216469 0.28604467 0.09141459]


In [46]:
# calculate max along the column
print(np.max(arr, axis=1)) 

[0.84493853 0.97396826 0.82565223 0.91112166 0.92245024]


In [47]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

0.9739682557652591
0.08569480601338675


In [48]:
## compute the indices of the min and max along a specified axis

# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[0 1 0 3 0]
[4 3 2 1 1]


In [49]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[4 1 1 3 2]
[1 4 4 1 0]


In [50]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

6
9


In [51]:
#compute element-wise min and max of two arrays

arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


In [52]:
#split fractional and integral parts of a floating-point array

arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.4777116  0.50639471 0.71175204 0.32413719 0.4068543  0.27048261
 0.56521106 0.66427211 0.11795484 0.13679153]
integral:  [4. 5. 9. 9. 8. 1. 5. 3. 9. 3.]


### compute the mean

In [53]:
# compute the overall mean
print(np.mean(arr))

0.5305660169139371


In [54]:
# compute the mean along the row
print(np.mean(arr, axis=0))

[0.52007032 0.56699396 0.44240069 0.51161211 0.611753  ]


In [55]:
# compute the mean along the column
print(np.mean(arr, axis=1))

[0.37894837 0.48273131 0.60077745 0.53307435 0.65729861]


### compute the median


In [56]:

# compute the overall median
print(np.median(arr))


0.5190077415876589


In [57]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[0.53369398 0.72391126 0.41550367 0.49749635 0.6487222 ]


In [58]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.30216469 0.34371331 0.62699782 0.51900774 0.6487222 ]


### compute the percentile

In [59]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.05316843 0.65509007 0.95625348]


### compute the standard deviation & variance

In [60]:
# compute the overall standard deviation
print(np.std(arr))

0.2513177588973816


In [61]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.24995922 0.3288065  0.12546734 0.14755405 0.30254694]


In [62]:
# compute the overall variance
print(np.var(arr))

0.06316061593720244


In [63]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.06247961 0.10811371 0.01574205 0.0217722  0.09153465]


In [64]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.06702695 0.10052908 0.03297142 0.04359291 0.02540956]


### compute the covariance & correlation

In [65]:
arr = np.random.rand(5,8)

In [66]:
print(np.cov(arr))

[[ 0.05746117 -0.01351749 -0.01513195  0.031365   -0.00441848]
 [-0.01351749  0.01508505  0.01488076  0.00678462  0.00737391]
 [-0.01513195  0.01488076  0.07255201  0.01402416 -0.02574586]
 [ 0.031365    0.00678462  0.01402416  0.07970201  0.03369905]
 [-0.00441848  0.00737391 -0.02574586  0.03369905  0.06463992]]


In [67]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[1.         0.52402852]
 [0.52402852 1.        ]]


### compute cumulative sum & product

In [68]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0)) 

[[0.88300677 0.94070899 0.7588901  0.43399206 0.93750418 0.30066107
  0.59321586 0.58743422]
 [1.32376075 1.19107721 1.08937221 1.07691133 1.22152577 0.64685679
  0.94731849 0.91224009]
 [2.15229093 1.73686254 1.10774211 1.81848996 1.72369555 1.42575002
  1.44188213 1.22307785]
 [2.99157934 1.91020756 1.38601868 2.30263785 2.58356674 1.54096204
  1.7805706  1.75531803]
 [3.66992889 2.01540163 2.14130231 2.85955894 3.10071114 1.9218325
  2.09521772 2.64582265]]


In [69]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))   

[[0.88300677 0.94070899 0.7588901  0.43399206 0.93750418 0.30066107
  0.59321586 0.58743422]
 [1.32376075 1.19107721 1.08937221 1.07691133 1.22152577 0.64685679
  0.94731849 0.91224009]
 [2.15229093 1.73686254 1.10774211 1.81848996 1.72369555 1.42575002
  1.44188213 1.22307785]
 [2.99157934 1.91020756 1.38601868 2.30263785 2.58356674 1.54096204
  1.7805706  1.75531803]
 [3.66992889 2.01540163 2.14130231 2.85955894 3.10071114 1.9218325
  2.09521772 2.64582265]]


In [70]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0)) 

[[0.88300677 0.94070899 0.7588901  0.43399206 0.93750418 0.30066107
  0.59321586 0.58743422]
 [0.38918875 0.23552363 0.2507996  0.27902186 0.26627143 0.10408758
  0.2100593  0.19080208]
 [0.32245462 0.12854534 0.00460716 0.20691665 0.13371346 0.08107311
  0.10388769 0.05930849]
 [0.27063243 0.0222827  0.00128207 0.10017826 0.11497636 0.0093406
  0.03518556 0.03156636]
 [0.18358339 0.00234401 0.00096832 0.05579139 0.05945938 0.00355756
  0.01107104 0.02810999]]


In [71]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))

[[8.83006768e-01 8.30652407e-01 6.30373891e-01 2.73577265e-01
  2.56479831e-01 7.71135015e-02 4.57449521e-02 2.68721504e-02]
 [4.40753984e-01 1.10350788e-01 3.64689611e-02 2.34465979e-02
  6.65933994e-03 2.30543495e-03 8.16360583e-04 2.65158710e-04]
 [8.28530173e-01 4.52199618e-01 8.30685925e-03 6.16018931e-03
  3.09346093e-03 2.40947578e-03 1.19163910e-03 3.70406420e-04]
 [8.39288411e-01 1.45486469e-01 4.04854754e-02 1.96009572e-02
  1.68542983e-02 1.94181779e-03 6.57671296e-04 3.50039088e-04]
 [6.78349559e-01 7.13583505e-02 5.38957942e-02 3.00157047e-02
  1.55224536e-02 5.91204407e-03 1.86020764e-03 1.65652350e-03]]


### element-wise comparison

In [72]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [73]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]
