## Numpy Data Types

Numpy has the following data types:

int
float
complex
bool
string
unicode
object
The numeric data types have various precisions like 32-bit or 64-bit.

Numpy data types can be represented using either Type or Type Code

In [2]:
import numpy as np
import pandas as pd

In [5]:
dtypes = pd.DataFrame(
    {
        'Type': [
            'int8', 
            'uint8', 
            'int16', 
            'uint16', 
            'int or int32', 
            'uint32', 
            'int64', 
            'uint64', 
            'float16', 
            'float32', 
            'float or float64',
            'float128', 
            'complex64', 
            'complex or complex128', 
            'bool', 
            'object', 
            'string_',
            'unicode_',
        ],
        
        'Type Code': [
            'i1', 
            'u1', 
            'i2', 
            'u2', 
            'i4 or i', 
            'u4', 
            'i8', 
            'u8', 
            'f2', 
            'f4 or f', 
            'f8 or d', 
            'f16 or g', 
            'c8', 
            'c16', 
            None, 
            'O', 
            'S', 
            'U',
        ]
    }
)

dtypes

Type Type Code
0                    int8        i1
1                   uint8        u1
2                   int16        i2
3                  uint16        u2
4            int or int32   i4 or i
5                  uint32        u4
6                   int64        i8
7                  uint64        u8
8                 float16        f2
9                 float32   f4 or f
10       float or float64   f8 or d
11               float128  f16 or g
12              complex64        c8
13  complex or complex128       c16
14                   bool      None
15                 object         O
16                string_         S
17               unicode_         U

In [6]:
1.1 - 0.9

0.20000000000000007

In [8]:
round(1.1 -.9,1)

0.2

In [9]:
arr = np.array([1,2,3], dtype='f4')
arr

array([1., 2., 3.], dtype=float32)

In [10]:
# Identical to the above
arr = np.array([1,2,3], dtype='float32')
arr.dtype

dtype('float32')

In [12]:
arr = np.array([1,2,"3.4"], dtype='float32')
arr.dtype

for i in arr:
    print(type(i))
    
print(arr[2]+3)

<class 'numpy.float32'>
<class 'numpy.float32'>
<class 'numpy.float32'>
6.400000095367432


In [13]:
arr = np.array(["1","2","3"], dtype='int')
print(arr.dtype)

for i in arr:
    print(i)

int32
1
2
3


In [14]:
arr = np.array([1,2,"3"], dtype='float32')
arr.dtype

for i in arr:
    print(type(i))
arr

<class 'numpy.float32'>
<class 'numpy.float32'>
<class 'numpy.float32'>


array([1., 2., 3.], dtype=float32)

In [15]:
arr = np.array([1.1,2.2,"3"], dtype='int')
print(arr.dtype)

for i in arr:
    print(i)

int32
1
2
3


In [16]:
arr = np.array([1+2j, 3-4j], dtype=np.complex64)
print(arr[0])
arr.dtype

(1+2j)


dtype('complex64')

In [17]:
arr = np.array([1,2,3], dtype='int16') # 16 / 8 = 2 ==> 2 bytes
print('Original Data Type: ' + str(arr.dtype))

arr = arr.astype(np.float32) # convert arr type from int16 --> float32 ( 8 bytes )
print('Data Type After Conversion: ' + str(arr.dtype))
arr

Original Data Type: int16
Data Type After Conversion: float32


array([1., 2., 3.], dtype=float32)

In [18]:
# An example of integer overflow at downcasting
arr = np.array([126,127,129], dtype='int16')
print('np array before type conversion: ' + str(arr))
#print(arr.max())
# Range of int8 [-128, 127], 256 overflows after conversion
arr = arr.astype('int8')
print('np array after type conversion: ' + str(arr))

np array before type conversion: [126 127 129]
np array after type conversion: [ 126  127 -127]


In [19]:
# An example of truncated string
s = np.array(['Ahmed', 'Ali'], dtype='S3')
print(s)

# An example of truncated unicode
s = np.array(['abcd', 'maximum'], dtype='U3')
print(s)

[b'Ahm' b'Ali']
['abc' 'max']


In [20]:
arr = np.array(['a', 'ab', 'abc'], dtype=np.string_)
print('The array is ' + str(arr))
print('The data type is ' + str(arr.dtype) + ' because the longest string in the array is "abc" and its length is 3.')

arr = np.array(['a', 'abc', 'abcd'], dtype=np.unicode_)
print('The array is ' + str(arr))
print('The data type is ' + str(arr.dtype) + ' because the longest unicode in the array is "abcd" and its length is 4.')

The array is [b'a' b'ab' b'abc']
The data type is |S3 because the longest string in the array is "abc" and its length is 3.
The array is ['a' 'abc' 'abcd']
The data type is <U4 because the longest unicode in the array is "abcd" and its length is 4.


## Create an array from an iterable

Add blockquote

Such as

list
tuple
range
iterator
Notice that not all iterables can be used to create a numpy array, such as set and dict

In [21]:
mylist = [1,2,3,4,5]
arr = np.array(mylist)
print(arr)

l = [1,2,3,4,5]
print(l)

print(type(l))
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'list'>
<class 'numpy.ndarray'>
int32


In [22]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [23]:
arr = np.array(range(10,21,2) )
print(arr)
print(arr.dtype)

arr = arr.astype(np.int8)
arr.dtype

[10 12 14 16 18 20]
int32


dtype('int8')

 ### Create an array with specified data type

In [24]:
arr = np.array([  [1,2,3], [4,5,6]  ], dtype='i2')
print(arr)
print('Data Type: ' + str(arr.dtype))

[[1 2 3]
 [4 5 6]]
Data Type: int16


### Create an aray within specified range

In [25]:
# np.arange(start, stop, step)
arr = np.arange(0, 21, 3)  
print(arr)
print(type(arr))

[ 0  3  6  9 12 15 18]
<class 'numpy.ndarray'>


### Create an array of evenly spaced numbers within specified range

In [26]:
arr, step_size = np.linspace(0, 5, 8, endpoint=False, retstep=True)
print(arr)
print(arr.size)
print('The step size is ' + str(step_size))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
8
The step size is 0.625


### Create an array of random values of given shape

In [27]:
arr = np.random.rand(3,4)
print(arr)

[[0.48029071 0.67716053 0.72728012 0.12920642]
 [0.30035574 0.70356279 0.05113611 0.18675333]
 [0.6338567  0.41281453 0.57678467 0.90313674]]


### Create an array of zeros of given shape
np.zeros(): create array of all zeros in given shape
np.zeros_like(): create array of all zeros with the same shape and data type as the given input array

In [28]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64)
print(arr)
print()
#print(arr[0])
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Data Type: complex64


In [30]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.int16)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0 0]
 [0 0]
 [0 0]]
Data Type: int16


### Create an array of ones of given shape
np.ones(): create array of all ones in given shape
np.ones_like(): create array of all ones with the same shape and data type as the given input array

In [31]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [32]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int32


In [37]:
arr = np.array([[1,2], [3,4],[5,2147483647]])
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1]
 [1 1]
 [1 1]]
Data Type: int32


### Create an empty array of given shape
np.empty(): create array of empty values in given shape
np.empty_like(): create array of empty values with the same shape and data type as the given input array
Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [38]:
empty = np.empty((5,5))
print(empty)
print(empty.dtype)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.37962117e-306
  1.42413555e-306]
 [1.78019082e-306 1.37959740e-306 6.23057349e-307 1.02360935e-306
  1.69120416e-306]
 [1.78022342e-306 6.23058028e-307 1.06811422e-306 1.39071445e-307
  8.01097889e-307]
 [1.78020169e-306 7.56601165e-307 1.02359984e-306 1.42417221e-306
  7.56593017e-307]
 [6.89805151e-307 1.78020169e-306 1.42410974e-306 2.56761491e-312
  3.91786943e-317]]
float64


In [36]:
newarr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
empty = np.empty_like(newarr)
print(empty)
print('Data Type: ' + str(empty.dtype))

[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]
Data Type: int64


### Create an array of constant values of given shape
np.full(): create array of constant values in given shape
np.full_like(): create array of constant values with the same shape and data type as the given input array

In [39]:
full = np.full((4,4), 6)
print(full)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [40]:
arr = np.array([[1,2], [3,4.4]])
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


In [41]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


### Create an array in a repetitive manner

In [42]:
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 4)) 

[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5]


In [43]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(arr)
print()
print(np.repeat(arr, 3, axis=0)) 

[[0, 1, 2], [3, 4, 5]]

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [44]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5], [36,7,8]]
print(np.repeat(arr, 3, axis=0)) 

[[ 0  1  2]
 [ 0  1  2]
 [ 0  1  2]
 [ 3  4  5]
 [ 3  4  5]
 [ 3  4  5]
 [36  7  8]
 [36  7  8]
 [36  7  8]]


In [45]:
# An example of repeating along x-axis
arr = [[3],[4], [5]]
print(np.repeat(arr, 3, axis=1)) 

[[3 3 3]
 [4 4 4]
 [5 5 5]]


In [46]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1))

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [47]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [48]:
# Repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


### Create an identity matrix of given

In [49]:
identity_matrix = np.eye(4)
#identity_matrix = identity_matrix.astype(int)
print(identity_matrix)
print(type(identity_matrix))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [50]:
identity_matrix = np.eye(3).astype(int)
#identity_matrix = identity_matrix.astype(int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [51]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=2) # default k = 0
print(identity_matrix)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [52]:
identity_matrix = np.identity(5)
print(identity_matrix)
print(type(identity_matrix))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>


### Create an array with given values on the diagonal

In [53]:
arr = np.random.rand(5,5)
print(arr)
print("\n\n")
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.52860082 0.83816276 0.99133702 0.61933444 0.5820985 ]
 [0.97909108 0.75769036 0.40299854 0.79766524 0.98387186]
 [0.9627747  0.81013774 0.83334252 0.10503391 0.82750605]
 [0.94447791 0.47102642 0.34851549 0.45372408 0.03814432]
 [0.91865059 0.18659875 0.68206413 0.37509964 0.11310185]]



Values on the diagonal: [0.52860082 0.75769036 0.83334252 0.45372408 0.11310185]


In [54]:
# Not necessarily to be a square matrix
arr = np.random.rand(10,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.45217029 0.74759434 0.14692209]
 [0.96780438 0.38420649 0.96321119]
 [0.12798774 0.06148049 0.1306955 ]
 [0.13741829 0.7472841  0.78359915]
 [0.25274116 0.69536503 0.85394464]
 [0.10348901 0.51277898 0.58025832]
 [0.26225786 0.40385986 0.270492  ]
 [0.66131144 0.84213608 0.99936883]
 [0.17382237 0.9295339  0.59752306]
 [0.65660844 0.14120515 0.1371066 ]]
Values on the diagonal: [0.45217029 0.38420649 0.1306955 ]


In [55]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5,6])
print(arr)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
